"use client";

import { useState, useRef, useEffect, useTransition } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { MessageCircle, X, Send, Sparkles, User, Bot } from "lucide-react";
import { Input } from "@/components/ui/input";
import { refineTripAction } from "@/app/actions/generate-itinerary";
import type { GeneratedItinerary } from "@/lib/ai-agent";

function buildDiffSummary(before: GeneratedItinerary, after: GeneratedItinerary): string {
  const changes: string[] = [];

  // Compare activities by name per day (IDs may be regenerated by Claude)
  const beforeNames = new Set(before.days.flatMap((d) => d.activities.map((a) => a.name)));
  const afterNames  = new Set(after.days.flatMap((d) => d.activities.map((a) => a.name)));

  const added   = [...afterNames].filter((n) => !beforeNames.has(n));
  const removed = [...beforeNames].filter((n) => !afterNames.has(n));

  if (added.length)   changes.push(`Added: ${added.slice(0, 3).join(", ")}${added.length > 3 ? ` +${added.length - 3} more` : ""}`);
  if (removed.length) changes.push(`Removed: ${removed.slice(0, 3).join(", ")}${removed.length > 3 ? ` +${removed.length - 3} more` : ""}`);

  // Day theme changes
  const themeChanges = after.days.filter((d, i) => before.days[i] && before.days[i].theme !== d.theme).length;
  if (themeChanges > 0) changes.push(`${themeChanges} day theme${themeChanges > 1 ? "s" : ""} updated`);

  // Budget change
  if (before.totalBudget !== after.totalBudget) {
    const delta = after.totalBudget - before.totalBudget;
    changes.push(`Budget ${delta > 0 ? "+" : ""}$${delta.toLocaleString()}`);
  }

  if (changes.length === 0) return "Done! Your itinerary has been refreshed with the changes.";
  return `Done! Here's what changed:\n• ${changes.join("\n• ")}`;
}

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface AIChatAssistantProps {
  itinerary: GeneratedItinerary;
  onItineraryUpdate: (updated: GeneratedItinerary) => void;
}

const SUGGESTIONS = [
  "Make Day 2 more foodie",
  "Add a spa day",
  "Find cheaper alternatives",
  "Make it more adventurous",
];

export default function AIChatAssistant({ itinerary, onItineraryUpdate }: AIChatAssistantProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content: `I've crafted your ${itinerary.destination} trip! Ask me to refine any part — change a day's vibe, swap activities, adjust for budget, or anything else.`,
    },
  ]);
  const [input, setInput] = useState("");
  const [isPending, startTransition] = useTransition();
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  function sendMessage(text: string) {
    if (!text.trim() || isPending) return;
    const userMsg: Message = { role: "user", content: text };
    setMessages((m) => [...m, userMsg]);
    setInput("");

    startTransition(async () => {
      const snapshot = itinerary;
      const result = await refineTripAction(itinerary, text);
      if (result.success) {
        onItineraryUpdate(result.itinerary);
        setMessages((m) => [
          ...m,
          { role: "assistant", content: buildDiffSummary(snapshot, result.itinerary) },
        ]);
      } else {
        setMessages((m) => [
          ...m,
          { role: "assistant", content: `Sorry, I couldn't update that: ${result.error}` },
        ]);
      }
    });
  }

  return (
    <>
      {/* Floating button */}
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={() => setIsOpen(true)}
        className={`fixed bottom-6 left-6 z-40 flex items-center gap-2 px-4 py-3 rounded-2xl font-semibold text-sm bg-[#0f172a] text-white shadow-lg hover:shadow-xl transition-all ${isOpen ? "opacity-0 pointer-events-none" : ""}`}
      >
        <Sparkles className="w-4 h-4 text-[#00f5d4]" />
        Refine Trip
      </motion.button>

      {/* Chat panel */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 40, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 40, scale: 0.95 }}
            transition={{ duration: 0.25 }}
            className="fixed bottom-6 left-6 z-50 w-80 sm:w-96 bg-white rounded-3xl border border-slate-200 shadow-2xl overflow-hidden flex flex-col"
            style={{ maxHeight: "480px" }}
          >
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-slate-100 flex-shrink-0">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-[#0f172a] flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-[#00f5d4]" />
                </div>
                <div>
                  <p className="text-[#0f172a] font-semibold text-sm">AI Assistant</p>
                  <p className="text-slate-400 text-xs">Refine your itinerary</p>
                </div>
              </div>
              <button onClick={() => setIsOpen(false)} className="text-slate-400 hover:text-slate-600 transition-colors">
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3 min-h-0">
              {messages.map((msg, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex gap-2 ${msg.role === "user" ? "flex-row-reverse" : ""}`}
                >
                  <div
                    className="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
                    style={{
                      background: msg.role === "assistant" ? "#0f172a" : "#f1f5f9",
                    }}
                  >
                    {msg.role === "assistant"
                      ? <Bot className="w-3.5 h-3.5 text-[#00f5d4]" />
                      : <User className="w-3.5 h-3.5 text-slate-500" />}
                  </div>
                  <div
                    className="flex-1 px-3 py-2 rounded-2xl text-sm leading-relaxed"
                    style={{
                      background: msg.role === "assistant" ? "#f8fafc" : "#0f172a",
                      color: msg.role === "assistant" ? "#475569" : "#ffffff",
                    }}
                  >
                    {msg.content}
                  </div>
                </motion.div>
              ))}

              {isPending && (
                <div className="flex gap-2">
                  <div className="w-7 h-7 rounded-full bg-[#0f172a] flex items-center justify-center flex-shrink-0">
                    <Bot className="w-3.5 h-3.5 text-[#00f5d4]" />
                  </div>
                  <div className="px-3 py-2 rounded-2xl bg-[#f8fafc] border border-slate-100">
                    <div className="flex gap-1 items-center h-4">
                      {[0, 1, 2].map((i) => (
                        <motion.div
                          key={i}
                          className="w-1.5 h-1.5 rounded-full bg-slate-300"
                          animate={{ opacity: [0.4, 1, 0.4], y: [0, -3, 0] }}
                          transition={{ duration: 0.8, delay: i * 0.2, repeat: Infinity }}
                        />
                      ))}
                    </div>
                  </div>
                </div>
              )}
              <div ref={bottomRef} />
            </div>

            {/* Suggestions */}
            <div className="px-4 pb-2 flex gap-2 flex-wrap flex-shrink-0">
              {SUGGESTIONS.map((s) => (
                <button
                  key={s}
                  onClick={() => sendMessage(s)}
                  disabled={isPending}
                  className="text-xs px-3 py-1.5 rounded-full border border-slate-200 text-slate-500 hover:bg-slate-50 hover:border-slate-300 transition-colors disabled:opacity-40"
                >
                  {s}
                </button>
              ))}
            </div>

            {/* Input */}
            <div className="p-4 pt-2 flex gap-2 flex-shrink-0 border-t border-slate-50">
              <Input
                placeholder="Ask AI to refine your trip..."
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && sendMessage(input)}
                disabled={isPending}
                className="flex-1 bg-slate-50 border-slate-200 text-[#0f172a] placeholder:text-slate-400 focus:border-slate-400 focus:ring-1 focus:ring-slate-200 rounded-xl text-sm h-10"
              />
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => sendMessage(input)}
                disabled={isPending || !input.trim()}
                className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 bg-[#0f172a] disabled:opacity-40 hover:bg-[#1e293b] transition-colors"
              >
                <Send className="w-4 h-4 text-white" />
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
